# 学习记录管理定时任务配置

# 每小时执行一次数据处理
learn_data_process_hourly:
  command: 'learn:data:process'
  schedule: '0 * * * *'  # 每小时的第0分钟执行
  description: '每小时处理学习数据，计算有效学习时长'
  options:
    - '--date=today'
    - '--batch-size=100'

# 每30分钟执行一次异常检测
learn_anomaly_detect:
  command: 'learn:anomaly:detect'
  schedule: '*/30 * * * *'  # 每30分钟执行
  description: '检测学习异常行为'
  options:
    - '--date=today'
    - '--auto-resolve'
    - '--batch-size=50'

# 每天凌晨2点执行归档任务
learn_archive_daily:
  command: 'learn:archive'
  schedule: '0 2 * * *'  # 每天凌晨2点执行
  description: '归档完成的学习记录'
  options:
    - '--action=create'
    - '--format=json'
    - '--batch-size=20'

# 每天凌晨3点生成统计数据
learn_statistics_daily:
  command: 'learn:statistics'
  schedule: '0 3 * * *'  # 每天凌晨3点执行
  description: '生成每日学习统计数据'
  options:
    - '--batch-generate'
    - '--period=daily'
    - '--save'

# 每周日凌晨4点生成周统计
learn_statistics_weekly:
  command: 'learn:statistics'
  schedule: '0 4 * * 0'  # 每周日凌晨4点执行
  description: '生成每周学习统计数据'
  options:
    - '--batch-generate'
    - '--period=weekly'
    - '--days=7'
    - '--save'

# 每月1号凌晨5点生成月统计
learn_statistics_monthly:
  command: 'learn:statistics'
  schedule: '0 5 1 * *'  # 每月1号凌晨5点执行
  description: '生成每月学习统计数据'
  options:
    - '--batch-generate'
    - '--period=monthly'
    - '--days=30'
    - '--save'

# 每天凌晨1点清理过期档案
learn_archive_cleanup:
  command: 'learn:archive'
  schedule: '0 1 * * *'  # 每天凌晨1点执行
  description: '清理过期的学习档案'
  options:
    - '--action=cleanup'
    - '--days-before-expiry=30'

# 每天凌晨验证档案完整性
learn_archive_verify:
  command: 'learn:archive'
  schedule: '30 1 * * *'  # 每天凌晨1点30分执行
  description: '验证学习档案完整性'
  options:
    - '--action=verify'
    - '--batch-size=50'

# 每分钟清理无效的学习会话
learn_session_cleanup:
  command: 'train:learn-session:cleanup'
  schedule: '* * * * *'  # 每分钟执行
  description: '清理3分钟内未更新的活跃学习会话'
  options:
    - '--threshold=3' 