services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: true        # Make services public for testing

  Tourze\TrainRecordBundle\Command\:
    resource: '../../Command'
  Tourze\TrainRecordBundle\Procedure\:
    resource: '../../Procedure'
  Tourze\TrainRecordBundle\Repository\:
    resource: '../../Repository'
  Tourze\TrainRecordBundle\Service\:
    resource: '../../Service'
